services:
  # 1. The PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: fonu_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: fonu_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d fonu_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: fonu_api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DOCKER_ENV=true
      - DATABASE_URL=postgresql://admin:password123@db:5432/fonu_db?schema=public
      - JWT_SECRET=super_secret_jwt_key
      - WEBHOOK_SECRET='fonu_secret_123'
    volumes:
      # ONLY mount the src folder. 
      # This keeps the container's internal node_modules and config safe!
      - ./api/src:/app/src
    depends_on:
      db:
        condition: service_healthy

  # 3. The React Vite Frontend
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    container_name: fonu_web
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    volumes:
      # Bind mount for hot-reloading
      - ./web:/app
      - /app/node_modules
    depends_on:
      - api

volumes:
  pg_data: